### ISSUE TITLE
Assembly name conflict in 2021.3

### ISSUE THREAD

**Issue by erikbaender** [Chizaruu/com.unity.ide.vscode#19]
Hi,

First of all thanks for picking up the pieces Unity left behind and starting this project, hugely appreciate it!

Unfortunately I can't use your package in 2021.3 since there is an assembly conflict with the existing VS Code package from Unity that persists even if you remove it from the project first. It looks like pressing "Remove" doesn't actually do anything though since the package is still listed under Packages in the Project window. I also tried deleting the directory fom PackageCache manually but that didn't change anything either.
```
Assembly with name 'Unity.VSCode.Editor' already exists (Packages/com.tsk.ide.vscode/Editor/com.tsk.vscode.Editor.asmdef)
Assembly with name 'Unity.VSCode.Editor' already exists (Packages/com.unity.ide.vscode/Editor/Unity.com.unity.vscode.Editor.asmdef)
```

Is there any way to get around this? The editor is not usable while this error is not resolved, the scene view is completely magenta and the console is full of warnings about materials not getting created properly.

**Comment by erikbaender** [comment]
Nevermind, I didn't see that the VS Code package is also part of the Engineering collection which is installed by default. Not very intuitive that the package manager lets you manually press remove on packages in a collection and then acts as if it was actually removed.

**Comment by Chizaruu** [comment]
> Nevermind, I didn't see that the VS Code package is also part of the Engineering collection which is installed by default. Not very intuitive that the package manager lets you manually press remove on packages in a collection and then acts as if it was actually removed.

It's weird that Unity added it to their engineering collection, but good to know just in case someone has the same issue! :)
