### ISSUE TITLE
Unable to resolve Microsoft.Unity.Analyzers

### ISSUE THREAD

**Issue by citelkyuu** [Chizaruu/com.unity.ide.vscode#30]
I have complied with the prerequisites and instructions done within unity as instructed but I seem to be having issues regarding the analyzer:
![Capture](https://user-images.githubusercontent.com/131477534/233690253-04e9a72b-bb7d-4aa0-be33-07e06a35e99d.JPG)

I have everything up to date (Unity, VSCode, TSK Package, .Net 6&7 SDKs, VS 2022, .NET desktop build tools). I tried tinkering with the Ominsharp settings on VSCode such as `Enable Roslyn Analyzers` and `Use Modern Net` but there weren't any changes. I suspect some kind of issue with how the analyzer is being retrieved, since using the VS Code Editor Package provided by Unity while following [this guide](https://code.visualstudio.com/docs/other/unity) does not give me any errors.

**Comment by Chizaruu** [comment]
Weird. 

Can you let me know which OS you have running?

I'm unable to replicate your issue atm 😅

**Comment by citelkyuu** [comment]
I'm using Windows 10, its up to date as well. I forgot to mention, but I also installed the 4.7.1 Developer Pack and the targeting packs for .NET frameworks from 4.6 to 4.7.1. I've done this for Visual Studio Build Tools 2019 as well. Could this be causing some kind of interference somehow? Are there any directories I could be missing in PATH?

**Comment by NoTuxNoBux** [comment]
Is the Unity project set to use .NET Framework as opposed to .NET Standard 2.1?

IIRC the VSCode package from wackoisgod generates old non-SDK style projects for the former and SDK-style projects for the latter, but maybe this package only supports SDK-style projects? If so, perhaps having .NET Framework set in Unity triggers different behaviour in this package?

Out of curiosity: do you get the same error if you `dotnet restore` in the root of the project?

**Comment by Chizaruu** [comment]
> Is the Unity project set to use .NET Framework as opposed to .NET Standard 2.1?
> 
> IIRC, the VSCode package from wackoisgod generates old non-SDK style projects for the former and SDK-style projects for the latter, but maybe this package only supports SDK-style projects? If so, perhaps having .NET Framework set in Unity triggers different behaviour in this package?
> 
> Out of curiosity: do you get the same error if you `dotnet restore` in the project's root?

This package is compatible with the .NET Framework, but it does not support version 4.7.1. (For more information, refer to the PR at https://github.com/Chizaruu/com.tsk.ide.vscode/pull/28).

The package is designed to work with the 2021 LTS version of Unity (and above), which started using .NET Framework 4.8. You can find more details about Unity's .NET profile support at https://docs.unity3d.com/Manual/dotnetProfileSupport.html. The support for .NET Framework 4.8 was introduced in Unity 2021.2, as mentioned in the release notes available at [Release Notes](https://unity.com/releases/editor/whats-new/2021.2.0).

Considering the compatibility limitations, the issue can be closed.
