### ISSUE TITLE
Options to disable auto generation of config files

### ISSUE THREAD

**Issue by magenta404** [Chizaruu/com.unity.ide.vscode#31]
I am using a global omnisharp.json file which points to a global Microsoft.Unity.Analyzers.dll file as it saves on setup for various small test projects. When this package generates the omnisharp.json it overrides the global one.

Is it possible to have options to disable generation of each config file? Or perhaps a way to provide our own options to merge into the default ones this package generates?

**Comment by Chizaruu** [comment]
Excellent question; I'm sure it's possible to have them both be options.

I'll experiment and try to come up with the best solution.✌️

**Comment by magenta404** [comment]
Thanks!

**Comment by Chizaruu** [comment]
https://github.com/Chizaruu/com.tsk.ide.vscode/commit/8da03f5885c268eaecdfd904e6a324be9bf9b82a
I sorted out the current config auto-generation issue and need to implement custom arguments for each config.

~~It will hopefully be sorted out within the next hour.~~ ScrollView is a hassle.
