### ISSUE TITLE
Can't `dotnet build` the generated projects

### ISSUE THREAD

**Issue by frarees** [Chizaruu/com.unity.ide.vscode#34]
When building, I get:

```
C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(2073,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "ResolveProjectReferences"
```

Also, running `dotnet restore my.sln` works weird, it resolves only one project dependency at a time 🤔 

Is there a way to make the generated csprojs compilable with msbuild/dotnet build?

**Comment by frarees** [comment]
> Also, running dotnet restore my.sln works weird, it resolves only one project dependency at a time 🤔

This is what I mean

https://github.com/Chizaruu/com.tsk.ide.vscode/assets/220249/37f3fe6e-fd43-49ad-9998-c6fd15426ef5

**Comment by Chizaruu** [comment]
Which Unity version are you using, as this package only supports 2021.3 and above? 

I'm asking because I see your .sln says "Mini2020.".

**Comment by frarees** [comment]
Tested both on 2020.3.36 and 2021.3.16

**Comment by frarees** [comment]
I'm working on my own project generation library, and I'm hitting a similar issue. 

I'm not sure why a `restore` operation is required. Without it it won't compile. With it, it can hit the circular dependency issue, and also I only see one project being restored at a time. I have no idea how MSBuild works in this regard 🤷 

Unity's original old-style csprojs compile fine.

**Comment by frarees** [comment]
Created a small test example on pure .NET using `dotnet`. 4 project, the last one references the former 3. Upon restore, I see this:

![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/220249/655d0d7c-a0da-4ad6-9bd1-5beb8b8d04b5)

So there's nothing wrong with `dotnet restore` itself or my installation, it seems. What could be going on here? 🤔

**Comment by Chizaruu** [comment]
I started a [branch ](https://github.com/Chizaruu/com.tsk.ide.vscode/tree/34-cant-dotnet-build-the-generated-projects)on the matter, ~~`dotnet restore` should now work properly.~~ maybe not. Time for more testing.

Still working on trying to support `dotnet build`. :)

**Comment by frarees** [comment]
Noticed earlier today that per folder csproj fixes the problem. Not sure if that's a limitation, but per-project folders do the trick.

To compile properly I had to set `TargetFrameworks` to `netstandard2.1;net471` when compiling .NET Standard libraries, and `net471` when compiling .NET Framework libraries. `net48` won't do if one of your libraries references `System.Net.Http`.

**Comment by Chizaruu** [comment]
The per folder csproj works wonderfully! `dotnet restore` works as expected now!

![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/59434446/4d0cd15f-156a-4fac-8463-0ffc0c1a380b)

However I noticed that we get some weird skipping behaviour, it doesn't harm the intended purpose but its annoying to see. I'll see if I can solve this otherwise its fine as is.

```
dotnet restore 
  Determining projects to restore...
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Unity.VSCode.Editor\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Unity.VSCode.Editor\UnityEditor.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp\Unity.VSCode.Editor.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\Assembly-CSharp.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\UnityEditor.TestRunner\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp\InAssetFolder.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\UnityEditor.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\Unity.VSCode.Editor.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\InAssetFolder.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp\Unity.VSCode.Editor.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp\InAssetFolder.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\UnityEditor.TestRunner\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Unity.VSCode.Editor\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Unity.VSCode.Editor\UnityEditor.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\Assembly-CSharp.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\UnityEngine.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\UnityEditor.TestRunner.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\Unity.VSCode.Editor.csproj" because it was not found.
  Skipping project "B:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\CSharpProjFolders\Assembly-CSharp-Editor\InAssetFolder.csproj" because it was not found.
  All projects are up-to-date for restore.
  ```

**Comment by Chizaruu** [comment]
Promising update.. dotnet build works but.. oh so many warnings x_x

It's all about conflict resolutions though, and the arbitrary choices the process made. 
![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/59434446/d408ba44-6d23-4495-9c8c-82fa9111a8c1)

**Comment by Chizaruu** [comment]
Appending `.Shims` to the end of each `Include="{string} "` removes every warning in netstandard. However, I'm not entirely sure if it will negatively affect the .csproj or how it will affect the overall Unity Project.

**Without Shims** (Warning)
```xml
<Reference Include="System.Xml.Serialization">
      <HintPath>
        B:\Unity
        Editors\2021.3.14f1\Editor\Data\NetStandard\compat\2.1.0\shims\netfx\System.Xml.Serialization.dll</HintPath>
    </Reference>
```

**With Shims** (No Warning)
```xml
<Reference Include="System.Xml.Serialization.Shims">
      <HintPath>
        B:\Unity
        Editors\2021.3.14f1\Editor\Data\NetStandard\compat\2.1.0\shims\netfx\System.Xml.Serialization.dll</HintPath>
    </Reference>
```

Yeah, this was not a good idea.
