### ISSUE TITLE
Hitting "Regenerate" hangs Unity for ~25s

### ISSUE THREAD

**Issue by frarees** [Chizaruu/com.unity.ide.vscode#35]
### Current Behavior

![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/220249/ad06cdce-8e1f-4742-8280-ebe2dc73a55c)

### Reproduction / Steps To Reproduce

* Create a 2021 LTS project (I've used 2021.3.16)
* Include the package
* Click "Regenerate"

See how even on a minimal project it takes very long to generate the files.

I'm on a Windows 11 machine with mid-high CPU and GPU.

**Comment by Chizaruu** [comment]
Sorry that's my bad. I never got around to optimizing the regenerate process to only target the asmdefs that the user uses.
https://github.com/Chizaruu/com.tsk.ide.vscode/issues/23

**Comment by Chizaruu** [comment]
Alrighty, I added a new flag set to false by default, which should negate the unusually long time everyone currently needs to wait.

See https://github.com/Chizaruu/com.tsk.ide.vscode/commit/f2e9ad7e6983600b7593a151e75af8927a6b5e8d for more information.
![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/59434446/627f4ab8-637d-46a8-9b65-d0bef0e75770)

**Comment by Chizaruu** [comment]
Closing due to issue resolved. (hopefully)

See #36 for more information.
