### ISSUE TITLE
Project Generation doesn't work on Mac

### ISSUE THREAD

**Issue by jtsorlinis** [Chizaruu/com.unity.ide.vscode#41]
### Current Behavior

Trying to generate project files on mac errors saying "dotnet" command not found due to how process.Start() works on non windows platforms.

After a quick test, changing the lines in ProjectGeneration.cs like this seems to fix the issue, so we might need a flag based on OS

```
System.Diagnostics.ProcessStartInfo processStartInfo =
                new()
                {
                    FileName = "/bin/zsh",
                    Arguments = "-c \"dotnet build\"",
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
```

maybe something like `if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))` we can pass in different filename and arguments

**Comment by Chizaruu** [comment]
oh, that's not good.

I'll look into it and sort it out asap

**Comment by Chizaruu** [comment]
@jtsorlinis Let me know if my changes work. I don't have regular access to OSX. 😅 

`https://github.com/Chizaruu/com.tsk.ide.vscode.git#41-project-generation-doesnt-work-on-mac/com.tsk.ide.vscode`

**Comment by jtsorlinis** [comment]
Will test it now and let you know!

**Comment by jtsorlinis** [comment]
Had to change the url for package manager to `https://github.com/Chizaruu/com.tsk.ide.vscode.git?path=/com.tsk.ide.vscode#41-project-generation-doesnt-work-on-mac` but can confirm that the issue is now fixed on this branch! Thanks!

**Comment by Chizaruu** [comment]
Thanks! :)
