### ISSUE TITLE
jslib language server

### ISSUE THREAD

**Issue by Thaina** [Chizaruu/com.unity.ide.vscode#44]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Since unity have special file type, a `.jslib`, for webgl platform which actually emscripten extended `js` with macro and some other feature such as triple brace variable injection

I wish that unity vscode extension should support this language too. And so it would support autocomplete and not report error from those extended syntax

Is it possible?

### What type of pull request would this be?

Enhancement

**Comment by Chizaruu** [comment]
This isn't a vscode extension. o-o

**Comment by Chizaruu** [comment]
I'll add .jslib to the default extensions as I have no idea why it wasn't included originally but supporting autocomplete isn't possible, it would require its own vscode extension to support the jslib syntax

**Comment by Chizaruu** [comment]
I need clarification on what errors exactly it reports

**Comment by Thaina** [comment]
I see. I misunderstand a little bit and just thought that this repo also include vscode extension for unity

**Comment by Chizaruu** [comment]
I created a repo for Unity jslib support, but I'll be off and on in supporting it.

Currently, it just supports grammar and highlighting.
https://github.com/TheSleepyKoala/jslib-for-unity

I'll work on autocomplete when I have time (probably after my game's demo is released)

**Comment by Thaina** [comment]
Thank you very much
