### ISSUE TITLE
Some autogenerated omnisharp options are not placed in the right file

### ISSUE THREAD

**Issue by ershn** [Chizaruu/com.unity.ide.vscode#46]
### Current Behavior

The `omnisharp.json` settings file you can generate from the External Tools windows in Unity seems to include options that are only recognized by the C# vscode extension and not the omnisharp server.

![omnisharp_settings_generation](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/7790167/4225551e-ffd0-4008-b00d-2a306056999a)

The generated `omnisharp.json` file.
```json
{
    "RoslynExtensionsOptions": {
        "enableRoslynAnalyzers": true,
        "enableEditorConfigSupport": true,
        "analyzeOpenDocumentsOnly": true,
        "sdkIncludePrereleases": false,
        "organizeImportsOnFormat": true,
        "threadsToUseForAnalyzers": true,
        "useModernNet": true,
        "documentAnalysisTimeoutMs": 600000
    }
}
```

My understanding is that
- the `omnisharp.json` options are only read by the omnisharp server (they are not read by the C# vscode extension)
- the C# vscode extension options need to be set in vscode's `settings.json` to be recognized

Currently, some options that are only recognized by the C# vscode extension are set in `omnisharp.json` and are thus completely ignored.

Here is a table summarizing what option is recognized by who.

Option name | C# vscode extension option ? | Omnisharp server option ?
--- | --- | ---
`enableRoslynAnalyzers` | yes | no (the corresponding option is `EnableAnalyzersSupport`)
`enableEditorConfigSupport` | yes |  yes but not in `RoslynExtensionsOptions` (it's in `FormattingOptions`)
`analyzeOpenDocumentsOnly` | yes | yes but undocumented
`sdkIncludePrereleases` | yes | no
`organizeImportsOnFormat` | yes | no (the corresponding option is `OrganizeImports` in `FormattingOptions`)
`threadsToUseForAnalyzers` | no | no (was present in past versions as an `int` option)
`useModernNet` | yes | no
`documentAnalysisTimeoutMs` | no | yes

Note that the `threadsToUseForAnalyzers` option isn't used in the latest version of either the C# vscode extension or the omnisharp server. It was present in past versions of the omnisharp server, but as an `int` option.

### Reproduction / Steps To Reproduce

I didn't check every option but I checked the behavior of `organizeImportsOnFormat`.

### When the option is set in `omnisharp.json`

The imports are not reordered on save.

`omnisharp.json`
```javascript
{
    "RoslynExtensionsOptions": {
        // ...
        "organizeImportsOnFormat": true,
        // ...
    }
}
```

### When the option is set in vscode's `settings.json`

The imports are reordered on save.

`settings.json`
```javascript
"omnisharp.organizeImportsOnFormat": true,
```

### Anything else?

Omnisharp server options
- [Wiki](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options)
- [Source code for the RoslynExtensionsOptions option group](https://github.com/OmniSharp/omnisharp-roslyn/blob/v1.39.6/src/OmniSharp.Shared/Options/RoslynExtensionsOptions.cs)
  - Some options are not documented in the wiki

C# vscode extension options
- https://github.com/OmniSharp/omnisharp-vscode/blob/v1.25.8/src/omnisharp/options.ts

Omnisharp server option generation from the C# vscode extension
- https://github.com/OmniSharp/omnisharp-vscode/blob/v1.25.8/src/omnisharp/server.ts#L348-L441

_As a side note let me thank you for continuing the work on the vscode editor package for unity after unity support ended. It helped me fix non-functional refactoring actions in vscode after upgrading to Unity 2022.2._

**Comment by Chizaruu** [comment]
Right on, thanks for the in-depth analysis! 

I'll make the changes soon 😄

**Comment by ershn** [comment]
So fast !

Thank you.
