### ISSUE TITLE
Roslyn analyzers fail to detect issues when using absolute paths after initial use

### ISSUE THREAD

**Issue by Chizaruu** [Chizaruu/com.unity.ide.vscode#48]
### Current Behavior

After the first use, Roslyn analyzers cannot detect issues when absolute paths are used. Although the functionality remains intact, no problems are listed or underlined in the code.

![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/59434446/e114d2a7-6434-4007-aade-f6c5b97849e0)

### Stack Trace

<details>
<summary>Log</summary>
[dbug]: OmniSharp.Stdio.Host
        ************  Response (11.0294ms) ************ 
{
  "Request_seq": 25,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "CodeActions": [
      {
        "Identifier": "Roslynator.RCS1181",
        "Name": "Convert comment to documentation comment",
        "CodeActionKind": "QuickFix"
      },
      {
        "Identifier": "Roslynator.RCS1213",
        "Name": "Remove 'Update'",
        "CodeActionKind": "QuickFix"
      },
      {
        "Identifier": "Add_accessibility_modifiers",
        "Name": "Add accessibility modifiers",
        "CodeActionKind": "QuickFix"
      },
      {
        "Identifier": "\n    // Update is called once per frame\n    void Update()\n    {\n\n    }\n",
        "Name": "Remove empty Unity message",
        "CodeActionKind": "QuickFix"
      }
    ]
  },
  "Seq": 1641,
  "Type": "response"
}

[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 26,
  "Command": "/quickinfo",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Line": 13,
    "Column": 12
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (73.9076ms) ************ 
{
  "Request_seq": 26,
  "Command": "/quickinfo",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Markdown": "```csharp\nvoid TimTam.Update()\n```"
  },
  "Seq": 1644,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 27,
  "Command": "/v2/getcodeactions",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Line": 13,
    "Column": 9
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (56.1117ms) ************ 
{
  "Request_seq": 27,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "CodeActions": [
      {
        "Identifier": "Roslynator.RCS1213",
        "Name": "Remove 'Update'",
        "CodeActionKind": "QuickFix"
      },
      {
        "Identifier": "Add_accessibility_modifiers",
        "Name": "Add accessibility modifiers",
        "CodeActionKind": "QuickFix"
      },
      {
        "Identifier": "\n    // Update is called once per frame\n    void Update()\n    {\n\n    }\n",
        "Name": "Remove empty Unity message",
        "CodeActionKind": "QuickFix"
      }
    ]
  },
  "Seq": 1647,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 28,
  "Command": "/updatebuffer",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class TimTam : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n\n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n\n    }\n}\n"
  }
}
[dbug]: OmniSharp.Roslyn.BufferManager
        Updating file b:\GitHub\com.tsk.ide.vscode\Projects\2021.3 LTS\Assets\Custom Asmdef\TimTam.cs with new text:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TimTam : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }
}

[dbug]: OmniSharp.Stdio.Host
        ************  Response (1.8601ms) ************ 
{
  "Request_seq": 28,
  "Command": "/updatebuffer",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": true,
  "Seq": 1650,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 29,
  "Command": "/codecheck",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs"
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (0.2250ms) ************ 
{
  "Request_seq": 29,
  "Command": "/codecheck",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": []
  },
  "Seq": 1655,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 30,
  "Command": "/v2/codestructure",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs"
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (0.4086ms) ************ 
{
  "Request_seq": 30,
  "Command": "/v2/codestructure",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Elements": [
      {
        "Kind": "class",
        "Name": "TimTam",
        "DisplayName": "TimTam",
        "Children": [
          {
            "Kind": "method",
            "Name": "Start",
            "DisplayName": "Start()",
            "Children": null,
            "Ranges": {
              "full": {
                "Start": {
                  "Line": 7,
                  "Column": 4
                },
                "End": {
                  "Line": 10,
                  "Column": 5
                }
              },
              "name": {
                "Start": {
                  "Line": 7,
                  "Column": 9
                },
                "End": {
                  "Line": 7,
                  "Column": 14
                }
              }
            },
            "Properties": {
              "static": false,
              "accessibility": "private"
            }
          },
          {
            "Kind": "method",
            "Name": "Update",
            "DisplayName": "Update()",
            "Children": null,
            "Ranges": {
              "full": {
                "Start": {
                  "Line": 13,
                  "Column": 4
                },
                "End": {
                  "Line": 16,
                  "Column": 5
                }
              },
              "name": {
                "Start": {
                  "Line": 13,
                  "Column": 9
                },
                "End": {
                  "Line": 13,
                  "Column": 15
                }
              }
            },
            "Properties": {
              "static": false,
              "accessibility": "private"
            }
          }
        ],
        "Ranges": {
          "full": {
            "Start": {
              "Line": 4,
              "Column": 0
            },
            "End": {
              "Line": 17,
              "Column": 1
            }
          },
          "name": {
            "Start": {
              "Line": 4,
              "Column": 13
            },
            "End": {
              "Line": 4,
              "Column": 19
            }
          }
        },
        "Properties": {
          "static": false,
          "accessibility": "public"
        }
      }
    ]
  },
  "Seq": 1658,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 31,
  "Command": "/findusages",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Line": 4,
    "Column": 13,
    "OnlyThisFile": false,
    "ExcludeDefinition": true
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 32,
  "Command": "/findusages",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Line": 7,
    "Column": 9,
    "OnlyThisFile": false,
    "ExcludeDefinition": true
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 33,
  "Command": "/findusages",
  "Arguments": {
    "FileName": "b:\\GitHub\\com.tsk.ide.vscode\\Projects\\2021.3 LTS\\Assets\\Custom Asmdef\\TimTam.cs",
    "Line": 13,
    "Column": 9,
    "OnlyThisFile": false,
    "ExcludeDefinition": true
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (1.3936ms) ************ 
{
  "Request_seq": 32,
  "Command": "/findusages",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": []
  },
  "Seq": 1664,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (1.3925ms) ************ 
{
  "Request_seq": 33,
  "Command": "/findusages",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": []
  },
  "Seq": 1665,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response (6.8085ms) ************ 
{
  "Request_seq": 31,
  "Command": "/findusages",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": []
  },
  "Seq": 1661,
  "Type": "response"
}

</details>

### Anything else?

This issue was previously reported on the Omnisharp Roslyn repository in February. For more details, please refer to the following link: [Omnisharp Roslyn Issue #2506](https://github.com/OmniSharp/omnisharp-roslyn/issues/2506)

**Comment by Chizaruu** [comment]
It seems that the /v2/codestructure command is breaking something.

~~I seriously think I will need to take one of these two routes:~~

~~1. I start supporting an Omnisharp fork for Unity and integrate some hacky fixes.~~
~~2. I contribute to this alternative c# repo https://github.com/razzmatazz/csharp-language-server~~

MS just released a new [C# dev tools extension for VSCode.](https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/)

Let's suss it out for a bit. 🧑‍💻

**Comment by NoTuxNoBux** [comment]
I doubt the Roslyn issue is going to be fixed soon - is there perhaps a possibility to generate relative paths again since the `csproj` files are always in the same location?

Modern .NET SDK projects tend to not specify the compiled items at all any more, but I'm not sure if that's feasible with Unity - usually they are next to the files and folders they need to include when that's the case, but perhaps using a wild card on e.g. `Assets/Scripts/**` works?

**Comment by Chizaruu** [comment]
Well, the new dev kit extension fixes the Roslyn issue for Windows. :)

> I doubt the Roslyn issue is going to be fixed soon - is there perhaps a possibility to generate relative paths again since the `csproj` files are always in the same location?
>
> Modern .NET SDK projects tend to not specify the compiled items at all any more, but I'm not sure if that's feasible with Unity - usually they are next to the files and folders they need to include when that's the case, but perhaps using a wild card on e.g. `Assets/Scripts/**` works?

I'll check it out soon hopefully! (Been working hard on game dev lately) 

That's also an issue in itself. ;)
