### ISSUE TITLE
External Script Editor doesn't show option for VSCode

### ISSUE THREAD

**Issue by laicasaane** [Chizaruu/com.unity.ide.vscode#53]
### Current Behavior

External Script Editor doesn't show option for VSCode

### Reproduction / Steps To Reproduce

1. Follow the Prerequisites section to install all required components
2. Open a project in Unity 2022.3.0
3. Add `com.tsk.ide.vscode` via OpenUPM
4. Restart Windows
5. Open Unity project again
6. See there is still no VSCode option for External Script Editor

### Anything else?

OS: Windows 11
Visual Studio Code: 1.78.2

![image](https://github.com/Chizaruu/com.tsk.ide.vscode/assets/1594982/706d90cd-39e2-4743-85c1-6bbaf4ac1877)

**Comment by Chizaruu** [comment]
Do you still have the issue if you install via package manager?

### Unity

-   Open Window/Package Manager
-   Click +
-   Select Add package from git URL
-   Paste `https://github.com/Chizaruu/com.tsk.ide.vscode.git#upm` into URL
-   Click Add

**Comment by Chizaruu** [comment]
Do you know if there are any errors/warnings in the console?

**Comment by Chizaruu** [comment]
Note that I'm currently using 2022.3 on Windows 10 and I can't seem to recreate your issue 😅

**Comment by laicasaane** [comment]
I've tried both way of installing the package, via OpenUPM and git URL. But there is till no option for VSCode. Also, no warning or error in the Console too.

**Comment by laicasaane** [comment]
I've opened a project in Unity 2021.3 and curiously VSCode option doesn't show up too. This project has `com.unity.ide.vscode` installed.

**Comment by Chizaruu** [comment]
Seems to be a Unity issue :o

**Comment by Chizaruu** [comment]
Good luck!

 I will close this out since this issue isn't related to this package.

**Comment by laicasaane** [comment]
A workaround is manually selecting "Code.exe" from the installation folder.
