### ISSUE TITLE
Freeze on initial load (/bin/zsh not found, possibly Linux-specific)

### ISSUE THREAD

**Issue by NoTuxNoBux** [Chizaruu/com.unity.ide.vscode#54]
### Current Behavior

Unity hangs on `Initialize Script Compilers` when the package is installed and Unity is first started.

`Editor.log` shows the following:

```
Registering precompiled user dll's ...
Registered in 0,013931 seconds.
Asset Pipeline Refresh: Total: 0.100 seconds - Initiated by RefreshV2(NoUpdateAssetOptions)
Command '/bin/zsh' not found or not accessible.
UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
VSCodeEditor.ProjectGeneration:GetDotnetCommand () (at Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/ProjectGeneration/ProjectGeneration.cs:1101)
VSCodeEditor.ProjectGeneration:GenerateNugetJsonSourceFiles () (at Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/ProjectGeneration/ProjectGeneration.cs:1019)
VSCodeEditor.ProjectGeneration:GenerateAndWriteSolutionAndProjects () (at Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/ProjectGeneration/ProjectGeneration.cs:338)
VSCodeEditor.ProjectGeneration:Sync () (at Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/ProjectGeneration/ProjectGeneration.cs:246)
VSCodeEditor.VSCodeScriptEditor:SyncAll () (at Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/VSCodeScriptEditor.cs:608)
UnityEditor.CodeEditorProjectSync:SyncEditorProject () (at /home/bokken/build/output/unity/unity/Editor/Mono/CodeEditor/CodeEditorProjectSync.cs:21)

(Filename: Library/PackageCache/com.tsk.ide.vscode@1.4.1/Editor/ProjectGeneration/ProjectGeneration.cs Line: 1101)
```

### Reproduction / Steps To Reproduce

1. Add packages to `manifest.json` using steps from README.
2. Start Unity.

### Anything else?

All project files seem to be correctly generated; I see the `CSharpProjFolders` folder with all necessary projects inside it. `omnisharp.json` and friends are also present as expected.

I'm on Arch Linux x86-64 and using Unity 2021.3.15f1 (Linux editor).

**Comment by Chizaruu** [comment]
Wow, that's a really weird issue.

Do you have any of these shells?

- zsh
- bash
- ksh
- csh
- dash
- fish
- sh

**Comment by NoTuxNoBux** [comment]
Yes, I have:

* sh
* bash
* fish

If you need to do shell stuff on Linux, the most portable choice is `sh` since pretty much every distribution has it in some form or another. `bash` is also going to be fine in 99% of developer cases (e.g. Alpine Linux doesn't have it by default, but it's primarily popular for containers).

The other shells usually need to be installed manually in a distribution.

**Comment by NoTuxNoBux** [comment]
Hmmm, I installed `zsh` because it's the first shell and as test to see if it works, but it still hangs.

Could be the command is hanging for some reason (I see a `-c` though, so it should exit after the command) or the problem is somewhere else and it's just a red herring.

**Comment by Chizaruu** [comment]
Interesting, all the possible commads for shells are located here

```cs
case RuntimePlatform.LinuxEditor:
                case RuntimePlatform.OSXEditor:
                    possibleCommands = new string[]
                    {
                        "/bin/zsh",
                        "/bin/bash",
                        "/bin/ksh",
                        "/bin/csh",
                        "/bin/dash",
                        "/bin/fish",
                        "/bin/sh"
                    };
                    break;
```

Do you use `usr/bin/` or `/bin/`?

Edit: My biggest issue is that I mainly develop on Windows. Linux usage is limited to servers/websites, so that I may have inadvertently caused this issue.

**Comment by Chizaruu** [comment]
I spent the past two hours researching, trying to set up a VM for ArchLinux, and improving the code.

I did the following -

- Added 'usr' paths to the list of possible dotnet commands, expanding the compatibility
- Replaced the usage of `process.Close()` with `process.Dispose()` to properly release process resources. (apparently, a possible fix)
- Fail to set it up ArchLinux correctly (I allocated less than adequate disk space :P)

I'll do some testing later today, but if you feel like testing it out in its current state, feel free to use this URL

`https://github.com/Chizaruu/com.tsk.ide.vscode.git?path=/com.tsk.ide.vscode#54-freeze-on-initial-load-binzsh-not-found-possibly-linux-specific`

**Comment by Chizaruu** [comment]
There is also this from StackOverflow, that I need to look further into.
https://stackoverflow.com/questions/73345509/net-redirectstandardoutput-not-working-for-linux

**Comment by NoTuxNoBux** [comment]
> Do you use usr/bin/ or /bin/?

Actually both on Arch Linux - `/bin` is a symlink to `/usr/bin` here, so both will work :slightly_smiling_face: .

> I'll do some testing later today, but if you feel like testing it out in its current state, feel free to use this URL

It's the same situation, unfortunately.

> Fail to set it up ArchLinux correctly (I allocated less than adequate disk space :P)

If you want an easier way to set up Arch Linux, you can use [EndeavourOS](https://endeavouros.com/); it just installs Arch with some additional stuff preinstalled, but it has a graphical installer to get through the process more quickly.

I'm guessing that this issue probably also occurs on Ubuntu or other distributions - these kinds of issues are _usually_ not distribution-specific, though I can't say for sure yet, of course :slightly_smiling_face: .

**Comment by Chizaruu** [comment]
> Actually both on Arch Linux - /bin is a symlink to /usr/bin here, so both will work 🙂 .

Oh that's good to know!

> It's the same situation, unfortunately.

Was this before or after my PR? o-o

**Comment by NoTuxNoBux** [comment]
I _think_ it's fixed now. I tried the branch just before I posted it, but tried it again now and it doesn't seem to freeze any more :tada: . If it occurs again, I'll report back, thanks :slightly_smiling_face: .
