### ISSUE TITLE
Update README / Prereq / MacOS section with instructions for Omnisharp

### ISSUE THREAD

**Issue by keerthik** [Chizaruu/com.unity.ide.vscode#60]
After this line in the README under macOS:

> To avoid seeing "Some projects have trouble loading.

It would be helpful to add the following in some form:
In your VS Code user settings, ensure `"omnisharp.useModernNet": false` exists. This stops VS Code from using the version of Mono included in the official C# extension (6.0.X as of now from the latest version).
After installing the latest version of mono directly, set 
`"omnisharp.monoPath": "/Library/Frameworks/Mono.framework/Versions/Current"` (or whatever path you may have installed it to). This will use the version you just installed (6.12.X as of now).

Hopefully that will save a few more people 30 minutes after switching to this plugin from the official Unity one after updating their Unity editor!

**Comment by Chizaruu** [comment]
This package was designed to let you use Modern Net, though. :o

But more importantly, it allows you to use the new C# Dev Kit that Microsoft recently offered which I highly recommend, even in its preview state.
https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit

**Comment by Chizaruu** [comment]
I re-read your line. Wow. I didn't know the extension was downgrading your mono version.

**Comment by Chizaruu** [comment]
How does [this ](https://github.com/Chizaruu/com.tsk.ide.vscode/blob/60-update-readme-prereq-macos-section-with-instructions-for-omnisharp/README.md)sound?  @keerthik 

---

3. **[macOS only]** To avoid seeing "Some projects have trouble loading. Please review the output for more details", make sure to install the latest stable [Mono](https://www.mono-project.com/download/) release.
    1. In your Visual Studio Code (VS Code) user settings, ensure that the configuration `"omnisharp.useModernNet":` is set to `false`. This configuration must be in place to prevent VS Code from utilizing the Mono version included in the official C# extension (specifically, version 6.0.X as of the latest release).
    2. Upon installing the latest version of Mono directly, set the following configuration value:
    `"omnisharp.monoPath": "/Library/Frameworks/Mono.framework/Versions/Current"`
        - Ensure you replace the provided path with the location where you installed Mono. By doing so, VS Code will strictly utilize the newly installed version of Mono for all operations.

**Comment by Chizaruu** [comment]
If I may add, the prerequisites will change once the C# Dev kit is out of preview as we won't need to worry about omnisharp settings

**Comment by keerthik** [comment]
Oh I didn't know about the devkit, I'll likely switch to that myself.

Still, I imagine the readme will reference the C# extension until the Devkit is out of beta, so updating this section would make sense till then. You can close when you like, and thanks for maintaining this extension ♥️
