### ISSUE TITLE
GenerateNugetJsonSourceFiles invokes dotnet with incorrect Arguments

### ISSUE THREAD

**Issue by mifreundorfer** [Chizaruu/com.unity.ide.vscode#64]
### Current Behavior

On Windows the Process in `GenerateNugetJsonSourceFiles` invokes dotnet with `-c "dotnet build"` as arguments, which does not work, as there is no `-c` parameter in dotnet. This seems to be an artifact of calling dotnet through a shell process on Linux and MacOS.

The correct invokation would just have `build` as an argument. This begs the question as to why dotnet is invoked through a shell on Linux and MacOS in the first place.

### Reproduction / Steps To Reproduce

- Create a Unity Project on Windows and generate the Visual Studio Code Project files.
- Observe that there are no obj and bin folders being created next to the .csproj files, because `dotnet build` is not run.

**Comment by mifreundorfer** [comment]
Also noting that, since this functions purpose seems to be to restore the Nuget Packages, the correct command to invoke would be `dotnet restore` not `dotnet build`

**Comment by Chizaruu** [comment]
It was invoked through a shell due to this issue #41. Before then, the method looked like this.

```cs
void GenerateNugetJsonSourceFiles()
        {
            System.Diagnostics.Process process = new();

            System.Diagnostics.ProcessStartInfo processStartInfo =
                new()
                {
                    FileName = "dotnet",
                    Arguments = "build",
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

            process.StartInfo = processStartInfo;

            process.Start();

            process.Close();
        }
```

I'm happy to change how the method is used, provided it doesn't break support for this issue.
