### ISSUE TITLE
Omnisharp diagnostics don't work on Windows

### ISSUE THREAD

**Issue by mifreundorfer** [Chizaruu/com.unity.ide.vscode#66]
### Current Behavior

Due to an implementation detail in Omnisharp in the `/codecheck` LSP request, no diagnostics are reported on Windows.

This is caused by specifying absoulte file paths for the compile items in the csproj. The file paths generated by the package start with a captial drive letter, e.g. `C:\Project\Assets\MyScript.cs`, but the file paths that VSCode passes to Omnisharp start with a lowercase drive letter, e.g. `c:´\Project\Assets\MyScript.cs`.  

Due to Omnisharp using case sensitive comparison in the `/codecheck` request the file paths do not match and all diagnostics are dropped.

You could argue that this is a bug in Omnisharp and should probably fixed there, but the easiest workaround here would be to specify relative paths instead of absoulte paths.

### Reproduction / Steps To Reproduce

- On Windows, create a Unity Project and add a script file.
- Type a compile error into the script file and observe that no diagnostics are reported in VSCode.
- When running Omnisharp with debug logging, it can be seen that the `/codecheck` request returns an emtpy result.

**Comment by mifreundorfer** [comment]
I have also reported this to Omnisharp as [https://github.com/OmniSharp/omnisharp-roslyn/issues/2556](https://github.com/OmniSharp/omnisharp-roslyn/issues/2556)

**Comment by Chizaruu** [comment]
Have you been able to try using the C# Dev Kit yet? 

I don't have this issue when using it, unlike when I just use the C# extension. (I'm a Windows user)

**Comment by mifreundorfer** [comment]
Yes it actually works when using C# Dev Kit, because apparently the 2.0 version of the the C# extension does not use Omnisharp anymore but IntelliCode instead.

**Comment by mifreundorfer** [comment]
So guess its fine if Omnisharp fixes theirs with case insensitive comparison instead of working around it here.

**Comment by Chizaruu** [comment]
Well, it seems C# dev tools is the official way forward for Unity VSCode.

https://forum.unity.com/threads/update-on-the-visual-studio-code-package.1302621/page-4

Microsoft took over vscode support for unity
https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/

**Comment by Chizaruu** [comment]
I'm closing this due to https://github.com/Chizaruu/com.tsk.ide.vscode/commit/1234ba893341dc75dd1e7c3f31faf1c60f32f094, which removes Omnisharp instructions.
