### ISSUE TITLE
Generated config files overwrite existing files even though generation for them is disabled

### ISSUE THREAD

**Issue by mifreundorfer** [Chizaruu/com.unity.ide.vscode#67]
### Current Behavior

In a Project that does not have the `TSKDoNotDelete.txt` file, all config files are generated an overwrite existing files, even though generation for them is disabled in the Editor Settings.

This causes data loss, when you don't have your project in version control. Especially with the `.editorconfig` file.

Do away with the `TSKDoNotDelete.txt` file and don't force generation of the config files. This is important for users switching from the offical VSCode Package to this version, as they do not have the txt file and will have their settings overwritten.

### Reproduction / Steps To Reproduce

- Create a custom `.edtiorconfig` file and installt the plugin.
- Remove the `TSKDoNotDelete.txt` file.
- Observe that the `.editorconfig` file is overwritten, even though generation for it is disabled.

**Comment by Chizaruu** [comment]
Agreed, I'll work on rectifying this issue tomorrow.
