### ISSUE TITLE
Automate package versions

### ISSUE THREAD

**Issue by Chizaruu** [Chizaruu/com.unity.ide.vscode#9]
It sucks to forget.

**Comment by Thaina** [comment]
First thing I think would help is we should use `?path=/com.tsk.ide.vscode` instead of `#upm` maybe?

We then could use tag as package version

**Comment by Chizaruu** [comment]
Good idea, but I still need to use upm for openUPM 

It's ok; I've just been using GIT wrong 😅; I found out that I should be using [npm version](https://docs.npmjs.com/cli/v9/commands/npm-version)
